### ISSUE TITLE
Support faulty/slow/interrupted pod networking

### ISSUE THREAD

**Issue by mffiedler** [redhat-chaos/krkn#104]
One class of network chaos to support is for pod networking (vs host/node networking).  Scenarios might be:

- high latency networking environments
-networks that are expected to periodically disconnect (moving vehicles)
- poor quality networks (packet corruption, high tx retries, etc)

One possible way for Kraken to support these scenarios is via integration of Litmus experiments:
[Pod network latency](https://docs.litmuschaos.io/docs/pod-network-latency)
[Pod network loss](https://docs.litmuschaos.io/docs/pod-network-loss)
[Pod network corruption](https://docs.litmuschaos.io/docs/pod-network-corruption)

This issue might need to be broken out into multiple issues.

**Comment by chaitanyaenr** [comment]
This is now supported in Krkn thanks to @yogananth-subramanian at both pod and node level: https://github.com/redhat-chaos/krkn/blob/main/docs/pod_network_scenarios.md and https://github.com/redhat-chaos/krkn/blob/main/docs/network_chaos.md. Thanks.
