### ISSUE TITLE
Support for running node scenarios in containerzed mode

### ISSUE THREAD

**Issue by chaitanyaenr** [redhat-chaos/krkn#106]
Kraken currently has instructions on how to run the node scenarios in standalone mode: https://github.com/cloud-bulldozer/kraken/blob/master/docs/node_scenarios.md but it's missing instructions on setting up/mounting the cloud configs with the credentials to use for talking to the cloud API from within the container.

**Comment by obrienrobert** [comment]
@chaitanyaenr is there a workaround for this until the instructions are added? I was thinking it might be possible to mount AWS creds when running the container?

**Comment by chaitanyaenr** [comment]
Krkn-hub node scenarios is the supported way to run containerized Kraken: https://github.com/redhat-chaos/krkn-hub/blob/main/docs/node-scenarios.md. Closing the issue in favor of krkn-hub. Thanks.
