### ISSUE TITLE
Large Scale testing issues: continue and namespace calls

### ISSUE THREAD

**Issue by paigerube14** [redhat-chaos/krkn#286]
Duplicating [jira card ](https://issues.redhat.com/browse/CHAOS-105)here

We need to avoid using kubernetes functions that query all the namespaces and objects ( https://github.com/redhat-chaos/krkn/blob/main/kraken/plugins/pod_plugin.py#L34 ) given that it's going to be a very expensive call during the scale testing where we will have thousands of namespaces with tens of thousands objects - experienced this with cerberus where we fixed the function calls: https://github.com/redhat-chaos/cerberus/issues/67

In cerberus we just added PR to use the continue kubernetes python functionality
https://github.com/redhat-chaos/cerberus/pull/167

Will need to use this for all places where we are getting list of pods, pvc, namespaces etc

**Comment by chaitanyaenr** [comment]
Part of the issue should be resolved by https://github.com/arcalot/arcaflow-plugin-kill-pod/pull/7. Thanks.

**Comment by chaitanyaenr** [comment]
Some of the improvements got merged, we should be good for now. Thanks.
