### ISSUE TITLE
Undefined litmus_installed

### ISSUE THREAD

**Issue by sandrobonazzola** [redhat-chaos/krkn#305]
In https://github.com/redhat-chaos/krkn/blob/main/run_kraken.py#L280 there's

```
        if litmus_uninstall and litmus_installed:
            common_litmus.delete_chaos(litmus_namespace)
            common_litmus.delete_chaos_experiments(litmus_namespace)
            common_litmus.uninstall_litmus(litmus_version, litmus_namespace)
```
introduced in pr #33.

but `litmus_installed` is not defined anywhere. My guess is that here `litmus_install` from https://github.com/redhat-chaos/krkn/blob/main/run_kraken.py#L50  was meant to be used after the change introduced with pr #292 .

@chaitanyaenr can you please handle?

**Comment by paigerube14** [comment]
This fix should now be in with PR: https://github.com/redhat-chaos/krkn/pull/316
