### ISSUE TITLE
Memory hog is not consuming resources as expected

### ISSUE THREAD

**Issue by chaitanyaenr** [redhat-chaos/krkn#321]
When running the memory hog scenarios, the resource usage is not matching the expected usage as defined in the config. For instance, during the run where where the usage is set to 100% of the available memory on a node, the actual usage is way too low. 

<img width="654" alt="Screen Shot 2022-09-11 at 11 02 07 PM" src="https://user-images.githubusercontent.com/14077093/189566340-7be8e9f4-91c2-412f-b7d5-46fc5b10ae63.png">

**Comment by sandrobonazzola** [comment]
Can you check if swap was available on the node?

**Comment by chaitanyaenr** [comment]
Closing the issue as we switched to arca based hog scenarios and they are working as expected. Thanks.
