### ISSUE TITLE
Example config for scenarios may not work OOTB

### ISSUE THREAD

**Issue by stratus-ss** [redhat-chaos/krkn#338]
For the scenarios I cloned the git repo. The path for all the files is in `krkn/scenarios/openshift/`

If you create the configmap like this:

```
oc create configmap scenarios-config  --from-file=krkn/scenarios/
```

The `openshift` folder is not copied into the pod. Therefore the default in the `config.yaml`  which prefixes all of the scenarios with `scenarios/openshift/` will fail to populate

If you create the configmap like this:

```
oc create configmap scenarios-config  --from-file=krkn/scenarios/openshift
```

The files populate into the container under `/root/scenarios/`. 

This causes a traceback:

```
Traceback (most recent call last):
  File "/root/kraken/run_kraken.py", line 429, in <module>
    main(options.cfg)
  File "/root/kraken/run_kraken.py", line 219, in main
    pod_scenarios.container_run(
  File "/root/kraken/kraken/pod_scenarios/setup.py", line 76, in container_run
    with open(container_scenario_config[0], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'scenarios/openshift/container_etcd.yml'
```

If I change the `mountPath` in the Kraken Job to this:
```
  - mountPath: "/root/kraken/scenarios/openshift"
              name: scenarios-config
```

This allows the pods to start.

So either the default config should have this mount path OR the `config.yaml` needs to remove the `openshift` folder from all of the scenarios listed in the default config

**Comment by chaitanyaenr** [comment]
Hi @stratus-ss, closing the issue as it should be fixed. Please feel free to re-open in case of any issues. Thanks.
