### ISSUE TITLE
VMware python package not cleanly installable

### ISSUE THREAD

**Issue by paigerube14** [redhat-chaos/krkn#340]
The vmware python package is not cleanly installing and causing actions to fail 

https://github.com/redhat-chaos/krkn/actions/runs/3198517493/jobs/5223134543

**Comment by paigerube14** [comment]
@janosdebugs I'm not sure, maybe something changed on their side. I see a lot of "fixes" using --user on the pip install line. Not sure if that's really a viable solution. Any thoughts?

**Comment by sandrobonazzola** [comment]
Going to change the requirement to take latest tagged version rather then main  branch head.
