### ISSUE TITLE
CAN NOT RUN KRKN pip install fails

### ISSUE THREAD

**Issue by agullon** [redhat-chaos/krkn#341]
I can not run krkn tests because `pip3 install -r requirements` fails: `ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-1cwjqpvc` 

Then, when I try to run tests:
```
Traceback (most recent call last):
    File "/opt/tools/krkn/run_kraken.py", line 5, in <module>
          import yaml
ModuleNotFoundError: No module named 'yaml'
```

I'm using Python 3.9.5 and running this script to test this issue:
```
#!/bin/bash

python3 -m venv py_env

source py_env/bin/activate

pip install --upgrade pip
pip install -r requirements.txt

python3 run.py

deactivate
```

run.py
```
import yaml
print("hello")
```

**Comment by sandrobonazzola** [comment]
This got solved by #343
