### ISSUE TITLE
Links under supported scenarios are broken

### ISSUE THREAD

**Issue by achuzhoy** [redhat-chaos/krkn#404]
There are 3 links to examples in the following url https://github.com/redhat-chaos/krkn/blob/main/docs/litmus_scenarios.md#supported-scenarios

All 3 appear to be broken.

**Comment by chaitanyaenr** [comment]
Thanks for reporting the ussue @achuzhoy. Hog scenarios have been migrated to https://github.com/redhat-chaos/krkn/blob/main/docs/arcaflow_scenarios.md from litmus. The issue should be fixed now, please free to re-open if any additional fixes are needed. Thanks.
