### ISSUE TITLE
Pod Scenarios - Wait for all containers to be running during recovery checks

### ISSUE THREAD

**Issue by lugi0** [redhat-chaos/krkn#413]
Currently, when running any pod scenario, after execution krkn will only wait for the Pod to be recreated in the cluster.
In my opinion, it would be better to also wait for all of the containers in the specified pod to be running/complete before moving to the next scenario. At the very least having a configurable key/option to do so would be very useful.

**Comment by chaitanyaenr** [comment]
We need to add two checks 1) check if the pods are in running state 2) check if ContainersReady status is true to https://github.com/redhat-chaos/arcaflow-plugin-kill-pod/blob/main/arcaflow_plugin_kill_pod.py#L287.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/redhat-chaos/arcaflow-plugin-kill-pod/pull/24. Thanks.
