### ISSUE TITLE
Centralized storage for chaos experiments artifacts

### ISSUE THREAD

**Issue by ashishkamra** [redhat-chaos/krkn#423]
Running chaos experiments in different environments results in a wealth of useful data that may have potential downstream applications such as for fine-tuning of large language models with such data for better triage of issues in production clusters. 

The ask is to provide functionality in krkn to 
1) gather the metadata such as description of the chaos scenario, cluster under test details, and so forth and resulting relevant logs - must gather, sosreports, etc (potentially truncated to save space) as a result of the chaos test, 
2) bundle everything up and send to a data store of choice (typically a S3 bucket but can be expanded into more data store choices down the road).

**Comment by chaitanyaenr** [comment]
Thanks for the pointers @ashishkamra! Wanted to provide a quick update on the progress with respect to this issue: 

Kudos to @tsebastiani, initial version of the telemetry service is live and accepting data ( https://ulnmf9xv7j.execute-api.us-west-2.amazonaws.com/production/download - needs credentials ) in addition to Kraken providing an option to the user to opt and ship data to a centralized location: https://github.com/redhat-chaos/krkn/blob/main/config/config.yaml#L69. Current version collects prometheus metrics and cluster + chaos metadata, we are planning to expand it to include alerts and must-gather/logs like suggested.

We have enabled it in prow CI runs and have data being collected for chaos test profiles and folks started consuming for AI/ML use cases.

**Comment by chaitanyaenr** [comment]
Closing the issue now that the feature has been added thanks to @tsebastiani. Enhancements are being tracked in separate issues. Thanks.
